eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8708
spring:
  application:
    name: eureka-service
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false